# Generated by Django 4.1.2 on 2022-11-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathsulmasail',
            name='deskripsi',
            field=models.TextField(default='ok'),
        ),
    ]
